apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
  labels:
    jenkins-agent: jenkins-agent
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    env:
    - name: JENKINS_URL
      value: "http://192.168.1.206:8080"
    - name: JENKINS_TUNNEL
      value: "192.168.1.206:50000"
    - name: JENKINS_SECRET
      valueFrom:
        secretKeyRef:
          name: jenkins-agent-secret
          key: secret
    - name: JENKINS_AGENT_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: JENKINS_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: JENKINS_AGENT_WORKDIR
      value: "/home/jenkins/agent"
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: REMOTING_OPTS
      value: "-noReconnectAfter 1d"
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/agent
    readinessProbe:
      tcpSocket:
        port: 22
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    livenessProbe:
      tcpSocket:
        port: 22
      initialDelaySeconds: 10
      periodSeconds: 20
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
  volumes:
  - name: workspace-volume
    emptyDir: {}
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 30 